package model;
// Generated Aug 22, 2017 4:01:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogFiles generated by hbm2java
 */
@Entity
@Table(name="log_files"
    ,catalog="sms"
)
public class LogFiles  implements java.io.Serializable {


     private Integer id;
     private String logName;
     private String detailDescription;
     private Date eventDate;
     private Date eventTime;
     private String location;
     private String description;

    public LogFiles() {
    }

    public LogFiles(String logName, String detailDescription, Date eventDate, Date eventTime, String location, String description) {
       this.logName = logName;
       this.detailDescription = detailDescription;
       this.eventDate = eventDate;
       this.eventTime = eventTime;
       this.location = location;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="log_name", nullable=false, length=45)
    public String getLogName() {
        return this.logName;
    }
    
    public void setLogName(String logName) {
        this.logName = logName;
    }

    
    @Column(name="detail_description", nullable=false, length=45)
    public String getDetailDescription() {
        return this.detailDescription;
    }
    
    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_date", nullable=false, length=19)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_time", nullable=false, length=19)
    public Date getEventTime() {
        return this.eventTime;
    }
    
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    
    @Column(name="location", nullable=false, length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


